# Generated by Django 5.1.4 on 2025-01-08 23:29

import data_analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyzer', '0002_csvfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVFile',
        ),
        migrations.AlterField(
            model_name='fichier',
            name='fichier',
            field=models.FileField(upload_to='uploads/', validators=[data_analyzer.models.validate_file_type]),
        ),
    ]
